aspell -t -c Ackn.tex
aspell -t -c Abstract.tex
aspell -t -c Introduction.tex
aspell -t -c Theory.tex
aspell -t -c Detector.tex
aspell -t -c Reconstruction.tex
aspell -t -c Measurement.tex
aspell -t -c Theory_Predictions.tex
aspell -t -c Alphas.tex
aspell -t -c Summary.tex
aspell -t -c Appendix.tex
aspell -t -c Hardware.tex
